FROM debian:9.8-slim AS spython-base
RUN export DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt upgrade -y
RUN apt install git grep libcurl4-openssl-dev r-base -y
RUN mkdir /app/
RUN cd /app/
RUN git clone https://github.com/AMarinhoSN/THEREALMcCOIL.git
RUN cd THEREALMcCOIL/
RUN cd categorical_method/
RUN R CMD SHLIB McCOIL_categorical_code.c llfunction_het.c
RUN sed -i '1s/.*/path="\/app\/THEREALMcCOIL\/categorical_method"/' test_R_code.R
RUN cd ../proportional_method/
RUN R CMD SHLIB McCOIL_prop_code.c llfunction.c
RUN sed -i '1s/.*/path="\/app\/THEREALMcCOIL\/proportional_method"/' test_R_code.R
CMD exec /bin/bash "$@"
